name: publish

on:
  release:
    types: [ published ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: 'gradle'
      - name: Run tests
        run: ./gradlew test
  publish:
    needs:
      - tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: 'gradle'
      - name: Set output
        id: vars
        run: |
          echo ${GITHUB_REF_NAME:1} 
          echo ::set-output name=version::${GITHUB_REF_NAME:0}
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run a Gradle build with
        run: ./gradlew build
      - name: Prepare to publish
        run: |
          echo '${{secrets.ORG_GRADLE_PROJECT_SIGNING_KEY}}' | base64 -d > secret.kbx
      - name: Publish to Maven Central
        env:
          ORG_GRADLE_PROJECT_SONATYPE_USERNAME: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_SONATYPE_PASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPE_PASSWORD }}
          RELEASE_VERSION: ${{ steps.vars.outputs.version }}
        run: |
          ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository \
            -Psigning.secretKeyRingFile=secret.kbx \
            -Psigning.keyId=${{ secrets.ORG_GRADLE_PROJECT_SIGNING_KEY_ID }} \
            -Psigning.password=${{ secrets.ORG_GRADLE_PROJECT_SONATYPE_SIGNING_PASSWORD }} \
            -PcentralPortalUsername=${{ secrets.CENTRAL_PORTAL_USERNAME }} \
            -PcentralPortalPassword=${{ secrets.CENTRAL_PORTAL_PASSWORD }}
